version: 0.0
os: linux
files:
  - source: /home/ubuntu/.jenkins/workspace/abc/webapp/target/webapp.war
    destination: /var/lib/tomcat8/webapps/testenv10.war
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
